Description: Master stack which creates all required nested stacks

Resources:
  NetworkStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3.amazonaws.com/${TemplatePath}/security-stack.yml"

  ClusterStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3.amazonaws.com/${TemplatePath}/security-stack.yml"

  ServiceAuthentication:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3.amazonaws.com/${TemplatePath}/security-stack.yml"

ServiceAddress:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3.amazonaws.com/${TemplatePath}/security-stack.yml"

ServiceExchange:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3.amazonaws.com/${TemplatePath}/security-stack.yml"