Description: Master stack which creates all required nested stacks

Resources:
  NetworkStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://dexlk-cloud-formation.s3.amazonaws.com/template_network.yml"

  ClusterStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://dexlk-cloud-formation.s3.amazonaws.com/template_cluster.yaml"

  ServiceAuthentication:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://dexlk-cloud-formation.s3.amazonaws.com/template_service_authentication.yaml"

  ServiceAddress:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://dexlk-cloud-formation.s3.amazonaws.com/template_service_address.yaml"

  ServiceExchange:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://dexlk-cloud-formation.s3.amazonaws.com/template_service_exchange.yaml"