#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

# FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
# WORKDIR /app
# EXPOSE 80
# EXPOSE 443

# FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
# WORKDIR /src
# COPY ["DexLK.Address/DexLK.Address.csproj", "DexLK.Address/"]
# RUN dotnet restore "DexLK.Address/DEXLK.Address.csproj"
# COPY . .
# WORKDIR "/src/DexLK.Address"
# RUN dotnet build "DexLK.Address.csproj" -c Release -o /app/build

# FROM build AS publish
# RUN dotnet publish "DexLK.Address.csproj" -c Release -o /app/publish

# FROM base AS final
# WORKDIR /app
# COPY --from=publish /app/publish .
# ENTRYPOINT ["dotnet", "DexLK.Address.dll"]

##############################################################################

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS base
WORKDIR /app
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true  
ENV ASPNETCORE_URLS=http://+:80  
EXPOSE 80  

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["DexLK.Address.csproj", "./"]
RUN dotnet restore "./DexLK.Address.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "DexLK.Address.csproj" -c Release -o /app
FROM build AS publish
RUN dotnet publish "DexLK.Address.csproj" -c Release -o /app
FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DexLK.Address.dll"]